### ISSUE TITLE
Networked Machine UI Error: ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by dhdadev** [substrate-developer-hub/substrate-front-end-template#151]
Hi,
   I have been able to successfully launch a substrate-node-template node on my mac via this command:
./target/release/node-template --dev --ws-external
Then I kick off the substrate-front-end template, yarn start...and all seems well. My web browser locally is able to open localhost:8000 and display everything correctly, but if I try the supplied http://IP:8000 on a different machine, in the same network this is what I get:
API-WS: disconnected from ws://127.0.0.1:9944: 1006:: Abnormal Closure
Followed by: failed: Error in connection establishment:  net::ERR_CONNECTION_REFUSED
Two questions, has anyone else seen this before, and secondly is there a way to solve this issue?
Thanks for your time 

Edit: I am using Chrome as my browser

**Comment by wheresaddie** [comment]
Unfortunately afaik this is a Chrome specific behavior. Chrome doesn't allow unsecure websocket (ws) connections to localhost (only wss, so you should setup a TLS certificate for your local web/websocket server). But the same should work without any issues in Firefox and other browsers. cc @riusricardo please confirm

This particular problem is intentional, and they have made this change to make Chrome more secure by preventing attacks against internal network devices and processes listening on localhost which is sad news for us.. 

https://bugs.chromium.org/p/chromium/issues/detail?id=378566

**Comment by danforbes** [comment]
The error states `disconnected from ws://127.0.0.1:9944`. You need to make sure that the machine on which the node is running is accessible from the machine on which the front-end is running and then use the IP address of the machine on which the node is running as opposed to `127.0.0.1`, which most likely refers to `localhost` (the machine on which the front-end is running).

**Comment by dhdadev** [comment]
So just wanted to say thank you, for your help. With @danforbes answer I was able to change the development.json and relaunch my local node. This seemed to do the trick, I also launched the node-template with the --rpc-external --ws-external flags and all browers seem to work now.
Thank you very much for the help!

**Comment by danforbes** [comment]
Glad to hear it, @dhdadev :rocket:
