### ISSUE TITLE
Error Connecting to Substrate { "isTrusted": true }

### ISSUE THREAD

**Issue by PhuongHoang1182** [substrate-developer-hub/substrate-front-end-template#186]
can any one help me with this issue? 
 
![image](https://user-images.githubusercontent.com/30220537/125454118-3882bc92-5077-46d8-8bd6-463da6155669.png)

**Comment by NukeManDan** [comment]
Your node Template must be running and you need to have the default ws port 9944 set on it. See here
https://substrate.dev/docs/en/tutorials/create-your-first-substrate-chain/

**Comment by t1m0t** [comment]
Hi, I get the same issue while following the tutorial here https://substrate.dev/docs/en/tutorials/create-your-first-substrate-chain/interact .
@PhuongHoang1182 Have you found a solution?
Thanks

**Comment by NukeManDan** [comment]
If your node is remote, you need to configure your wss certificates correctly on that node. More info in the notes and references here
https://substrate.dev/docs/en/tutorials/start-a-private-network/alicebob#attach-a-ui

**Comment by t1m0t** [comment]
@NukeManDan I would expect the tutorial to be working as a remote host as it is suggested when you do `yarn start` but it is not the case. As I am begginner and I am not aware of some subtilities. Maybe the document could augmented regarding this case.

**Comment by NukeManDan** [comment]
where is there a reference to remote hosts working? Happy to make the docs more clear here of course! 😁

**Comment by PhuongHoang1182** [comment]
@t1m0t I got it to work with https://substrate.dev/docs/en/tutorials/create-your-first-substrate-chain/.  Thank to @NukeManDan

**Comment by t1m0t** [comment]
@PhuongHoang1182 are you sure you got it worked with remote host with just following the tutorial without tweaking something? 
Well, actually I would have expect from you guys and that I found myself is adding ssh local forwarding. It is actually suggested in the private network part. And the command would be as follow: `ssh -L 9944:127.0.0.1:9944 subs@192.168.0.170 -N -f`
Thanks anyway :)

**Comment by DrStoop** [comment]
### Missing `--ws-external --rpc-external` options in tutorial command [`./target/release/node-template --dev --tmp`](https://substrate.dev/docs/en/tutorials/create-your-first-substrate-chain/interact) solved it for me

To successfully attach the tutorial front-end to the tutorial node instead of using the [command in the tutorial](https://substrate.dev/docs/en/tutorials/create-your-first-substrate-chain/interact) `./target/release/node-template --dev --tmp` I use:

`./target/release/node-template --dev --tmp --ws-external --rpc-external`

With the tutorial command the node starts normally but the front-end connection fails with mentioned `{ "isTrusted": true }`.

#### Note:
I'm actually running everything in a ubuntu docker container but with published exporter port 9615 and listening port 9944. The Front-end is reachable from the firefox webbrowser within the container as well as of the host outside.
