### ISSUE TITLE
Custom Types Component

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/substrate-front-end-template#22]
Related to #16 and https://github.com/substrate-developer-hub/substrate-ui-template/commit/800bd2be323c6cd2dcfae6b827ea5e255ca015e1

We should see if we can avoid the UI vomiting if there are missing types, and allow users to specify new types right in the UI.

**Comment by JoshOrndorff** [comment]
This seems like a step toward re-inventing [apps](https://github.com/polkadot-js/apps). Isn't the purpose of this template to be an example and starting point for writing dapp-specific UIs? If so the types for the dApp should be hard-coded, not exposed to the end user.

**Comment by shawntabrizi** [comment]
Could you explain the downside of including such a component?

**Comment by JoshOrndorff** [comment]
My concern is that it adds extra complexity, and may take away from the simple nature of the template so far. When a developer forks the template ui to build their dapp-specific UI they will likely have to strip this feature out (or leave it in despite being unnecessary and making the project larger).

Your last two points are good, but I wonder if it would be better to link to apps which is also hosted.

I won't block it if you write it though.

**Comment by shawntabrizi** [comment]
@JoshOrndorff I think you are totally imagining some implementation detail which does not need to exist. Statically defined types and dynamically defined types, to my understanding, can both be allowed.

Adding this component should not affect anything related to defining static types right now.

Further, a user who removes this component would have no behavioral changes around static types.

If you know something I don't about why this wouldnt be the case, please call that out explicitly.

**Comment by shawntabrizi** [comment]
I also think you need see that having a user "go to apps" is not always the right solution here.

Any tutorial where we need to introduce Apps, we also need to introduce how a user uses and interacts with Apps.

For example in the Kitties tutorial, we tell users to use apps for the first half of the tutorial, and then all of the sudden for UI development, they use an entirely different piece of software.

I am not saying that this is not a pattern which we will end up doing, certainly the UI Template will not be able to do everything the Apps can do, but if this enables us to avoid showing a user two UIs, and thus simplify the developer learning curve, then it is totally worth it.

**Comment by ltfschoen** [comment]
I think the following improvements could be made:

1) Update https://substrate.dev/docs/en/tutorials/substrate-front-end/ so it mentions that it's already setup for DApp devs to define their Custom Types in src/config/common.json or otherwise Chain State queries will return an error.
2) Update this repo's README.md https://github.com/substrate-developer-hub/substrate-front-end-template/blob/master/README.md so there's an additional configuration step (i.e. configure Custom Types). So the steps would be Configure, Install, Start.

The reasoning for suggesting the above is summarised below based on my developer experience trying to integrate this front-end into my Substrate Kitties-like custom runtime.

I found out about this repo from the Riot chatrooms.
I just followed this README.md's instructions and started up the front-end (i.e. `yarn; yarn start`).
I then tried to create a kittie by creating an Extrinsic `createKitty`, which is where I encountered an error and raised this issue https://github.com/substrate-developer-hub/substrate-front-end-template/issues/46
But I modified the code to resolve the issue so I could create the kittie.
Then I wanted to view the kittie so I used the Chain State section of the UI to query `kitties`, but it didn't work.
So I knew I needed to add the Custom Types.
I then looked for where the Polkadot.js API connection was in the code and I found it in useSubstrate.js `let _api = await ApiPromise.create({ provider, types });`, so I just added my custom types there and it worked (even though I later found out that this wasn't necessary)
So I started creating a PR, thinking this should be a configuration option for DApp devs.
But then I found it already existed in the codebase within src/config/common.json, and all I had to do was add my Custom Types under `"CUSTOM_TYPES"`, so the PR wasn't necessary

**Comment by jimmychu0807** [comment]
@ltfschoen See if the latest [readme](https://github.com/substrate-developer-hub/substrate-front-end-template/blob/master/README.md) have addressed your four points. 

And thanks for adding the Custom Type link :).

**Comment by shawntabrizi** [comment]
@jimmychu0807 do you think it would be possible for each component to have its own "type" configuration right in the file, which then feeds to the API?

**Comment by jimmychu0807** [comment]
Currently the `ApiPromise` is being called once only when the app is loaded. So without changing the logic, the "type" is going to be an aggregated whole of all possible "types" that are used by all components.

**Comment by shawntabrizi** [comment]
And when the app is loaded, we can't call into other components? I am of course inventing a feature, but it would be cool if each module template kept their types in their code/component file. Then the UI would just pull the type information from each file and combine it together.

**Comment by jimmychu0807** [comment]
I see. I think we can do it. So a component file also export out a `customType`, in addition to its component. And then in `config/index.js` to specify where these customType are defined and load them.

**Comment by shawntabrizi** [comment]
If it makes sense, it might be a cool idea to play around with, otherwise, we don't want to over engineer the `substrate-front-end-template`.

The ultimately goal is to keep things simple for the user to build on top of (and to understand to some extent)

**Comment by jimmychu0807** [comment]
@shawntabrizi Take a look at commit https://github.com/substrate-developer-hub/substrate-front-end-template/commit/a599517e8e6480248e6fd48a1991957721b89455. Is this what you mean by putting `CUSTOM_TYPES` inside the component? 

But there is no good custom types in the template. So this code cannot be merged into master. I am just illustrating a pattern.
