### ISSUE TITLE
Define scope of UI template

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/substrate-front-end-template#26]
Related to my comment https://github.com/substrate-developer-hub/substrate-ui-template/issues/22#issuecomment-528992292

It would be helpful to define what is and is not in scope for this template. Is it
1 an example and starting point for writing dapp-specific UIs
2 a stripped down version of Apps?
3 a replacement for bonds ui?
4 other?

So far I've thought of it as 1 and 3 but not 2.

Once we have consensus about what this template is for, we should add it to the readme to guide users in understanding what they can do with it and to guide contributors in knowing which features are in scope.

Here's my first attempt:

> The UI template is an example and starting point for creating user interfaces for Substrate-based dApps. It uses react and polkadot-api as its primary dependencies. It does not strive to be a general purpose blockchain interaction tool, that's what apps is for.

**Comment by shawntabrizi** [comment]
> So far I've thought of it as 1 and 3 but not 2.

This is correct to me.

I think more than that, it could be a general set of examples using the Polkadot JS API.

The principals to me are:

* Completely modular design. Every component should be able to be removed or added. Users should be able to paste their "jsx" component into repos or chats, and all you need to do is copy and paste it into this template to work.

* Dead, stupid, simple. The components in the UI should favor simplicity in how they are designed and implemented over "best practices".

* It never breaks no matter the Substrate UI it is hooked up to. See https://github.com/substrate-developer-hub/substrate-ui-template/issues/14

What you wrote seems fine, although I think generally anyone can put any component they want into the assuming they follow step 3.

I was, for example, thinking of embedding our first tutorial demo component in here, such that if you have a POE module, the component would pop up. Otherwise, it would hide itself from the user.
