### ISSUE TITLE
Unified account selection component

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/substrate-front-end-template#27]
Currently each component that allows submitting extrinsics (Transfer, Runtime Upgrade, and Extrinsics) have their own `Select from your accounts` field. This will be unintuitive in a dApp-specific UI.

A better design would be to have a single account selection component (maybe rendered across in a top bar?) that allows the user to choose their account once, and any extrinsics are sent from the one selected account. This is a familiar design pattern in web UIs.

For example, here in github, I choose my account once, and any actions I take come from my account. 
![image](https://user-images.githubusercontent.com/2915325/64457240-8ec20180-d09e-11e9-9bbd-e55877f629e6.png)

**Comment by shawntabrizi** [comment]
I think it is a generally good idea. I dunno if you can do this as a separate component or you would need embed it into the main "apps" part.

As long as complexity remains low, I think it makes sense.

**Comment by shawntabrizi** [comment]
Initial implementation is in and works better than how it was before.

Things that can continue to be improved before this issue is closed:

* Automatically select an account so user does not need to interact every time. Ideally it would select the first account available. defaultValue on the dropdown would also be set then.

* Move the "AccountSelector" component out of the App return, to keep that part of the code clean. I tried, but for some reason it wasn't updating the visual of the selected account.

* Identicons??? :)

* Add a label to the menu item

* Use menu for more stuff? I could see it being used for metadata about the user.

**Comment by shawntabrizi** [comment]
I just pushed this which greatly improves UX: https://github.com/substrate-developer-hub/substrate-ui-template/commit/c00ef01979e73379022aa7eaee6ff6d3877bd805

**Comment by shawntabrizi** [comment]
> * Add a label to the menu item
> * Move the "AccountSelector" component out of the App return, to keep that part of the code clean.

Both of these addressed here:

https://github.com/substrate-developer-hub/substrate-ui-template/pull/34

**Comment by shawntabrizi** [comment]
Selecting an initial user when the page loads is the last thing I think we really need and then we can close this main issue. Could not find a react friendly and simple way to do it yet.

**Comment by shawntabrizi** [comment]
This has been completed for a while now.
